import type OpenAI from "openai";
import fs from "fs";
import path from "path";
import os from "os";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { logger } from "../utils/logger.js";
import { botInstance } from "../scheduler/index.js";
import { InputFile } from "grammy";

export const generatePdfDef: OpenAI.ChatCompletionTool = {
    type: "function",
    function: {
        name: "generate_professional_pdf",
        description: "Creates and automatically sends a professional PDF document to the user. Use this when the user asks you to create a PDF of some content, structure, or report.",
        parameters: {
            type: "object",
            properties: {
                title: {
                    type: "string",
                    description: "The main title of the document."
                },
                author: {
                    type: "string",
                    description: "Author name or context, e.g., 'Generated by Jovi AI'."
                },
                sections: {
                    type: "array",
                    description: "The structured content sections of the document.",
                    items: {
                        type: "object",
                        properties: {
                            heading: {
                                type: "string",
                                description: "The section heading."
                            },
                            content: {
                                type: "string",
                                description: "Paragraphs of text. Use \\n\\n for line breaks."
                            },
                            listItems: {
                                type: "array",
                                items: {
                                    type: "string"
                                },
                                description: "Optional bullet points for this section."
                            }
                        }
                    }
                }
            },
            required: ["title", "sections"],
            additionalProperties: false
        }
    }
};

interface PdfParams {
    title: string;
    author?: string;
    sections: Array<{
        heading?: string;
        content?: string;
        listItems?: string[];
    }>;
}

export async function executeGeneratePdf(args: PdfParams, userId?: number): Promise<string> {
    try {
        const doc = await PDFDocument.create();
        let page = doc.addPage([595.28, 841.89]); // A4 Size Default
        const font = await doc.embedFont(StandardFonts.Helvetica);
        const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);

        let yDir = 800; // Start near top margin
        const leftMargin = 50;
        const pageWidth = 595.28;
        const maxTextWidth = pageWidth - leftMargin * 2;

        // Custom text wrapper since pdf-lib is low-level
        const wrapText = (text: string, maxWidth: number, fontFace: any, fontSize: number) => {
            const words = text.split(" ");
            const lines: string[] = [];
            let currentLine = "";

            for (const word of words) {
                const testLine = currentLine.length > 0 ? currentLine + " " + word : word;
                const width = fontFace.widthOfTextAtSize(testLine, fontSize);
                if (width > maxWidth) {
                    lines.push(currentLine);
                    currentLine = word;
                } else {
                    currentLine = testLine;
                }
            }
            if (currentLine) lines.push(currentLine);
            return lines;
        };

        const checkPageBreak = (neededRoom: number) => {
            if (yDir - neededRoom < 50) {
                page = doc.addPage([595.28, 841.89]);
                yDir = 800;
            }
        };

        // Title
        const titleFontSize = 24;
        const titleLines = wrapText(args.title, maxTextWidth, boldFont, titleFontSize);
        for (const line of titleLines) {
            checkPageBreak(30);
            page.drawText(line, { x: leftMargin, y: yDir, size: titleFontSize, font: boldFont, color: rgb(0, 0, 0) });
            yDir -= 30;
        }
        yDir -= 10;

        // Author
        if (args.author) {
            const authorFontSize = 12;
            checkPageBreak(20);
            page.drawText(args.author, { x: leftMargin, y: yDir, size: authorFontSize, font, color: rgb(0.4, 0.4, 0.4) });
            yDir -= 25;
        }

        // Section Loop
        for (const sec of args.sections) {
            if (sec.heading) {
                checkPageBreak(25);
                const headingFontSize = 16;
                const hLines = wrapText(sec.heading, maxTextWidth, boldFont, headingFontSize);
                for (const line of hLines) {
                    checkPageBreak(20);
                    page.drawText(line, { x: leftMargin, y: yDir, size: headingFontSize, font: boldFont, color: rgb(0, 0, 0) });
                    yDir -= 20;
                }
                yDir -= 5;
            }
            if (sec.content) {
                const paragraphs = sec.content.split(/\n+/);
                for (const pg of paragraphs) {
                    if (!pg.trim()) continue;
                    const contentFontSize = 11;
                    const lines = wrapText(pg.trim(), maxTextWidth, font, contentFontSize);
                    for (const line of lines) {
                        checkPageBreak(15);
                        page.drawText(line, { x: leftMargin, y: yDir, size: contentFontSize, font, color: rgb(0.1, 0.1, 0.1) });
                        yDir -= 15;
                    }
                    yDir -= 5;
                }
            }
            if (sec.listItems && sec.listItems.length > 0) {
                const contentFontSize = 11;
                for (const item of sec.listItems) {
                    if (!item.trim()) continue;
                    const lines = wrapText("• " + item.trim(), maxTextWidth - 10, font, contentFontSize);
                    for (let i = 0; i < lines.length; i++) {
                        checkPageBreak(15);
                        const xOffset = i === 0 ? 0 : 8;
                        page.drawText(lines[i], { x: leftMargin + 10 + xOffset, y: yDir, size: contentFontSize, font, color: rgb(0.1, 0.1, 0.1) });
                        yDir -= 15;
                    }
                }
                yDir -= 10;
            }
            yDir -= 15;
        }

        const pdfBytes = await doc.save();
        const safeTitle = args.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const timestamp = Date.now();
        const outputFileName = `jovi_${safeTitle}_${timestamp}.pdf`;
        const tempFilePath = path.join(os.tmpdir(), outputFileName);

        fs.writeFileSync(tempFilePath, pdfBytes);
        logger.info("PDF file successfully saved using pdf-lib.", { path: tempFilePath });

        if (userId && botInstance) {
            try {
                await botInstance.api.sendDocument(userId, new InputFile(tempFilePath), {
                    caption: `📄 Here is your professional PDF: *${args.title}*`,
                    parse_mode: "Markdown"
                });
                logger.info("PDF sent to user via Telegram.");
            } catch (tgError) {
                logger.error("Failed to send PDF to user via Telegram.", { error: String(tgError) });
                return "Error: Could not automatically send the file over Telegram, but it was generated.";
            } finally {
                setTimeout(() => {
                    try {
                        if (fs.existsSync(tempFilePath)) fs.unlinkSync(tempFilePath);
                    } catch (e) {
                        logger.warn("PDF cleanup failed.", { error: String(e) });
                    }
                }, 10000);
            }
        } else {
            logger.warn("No userId or botInstance provided. File was generated locally but not sent.");
        }

        return `Successfully generated professional PDF and sent to user: ${outputFileName}`;
    } catch (error) {
        logger.error("Failed to generate PDF using pdf-lib", { error: error instanceof Error ? error.message : String(error) });
        return `Error: Failed to generate PDF: ${String(error)}`;
    }
}
